// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eraghkejpujijvdsyuox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYWdoa2VqcHVqaWp2ZHN5dW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzU0NDQsImV4cCI6MjA1ODUxMTQ0NH0.6YhBcBhvSwtNiU1UKzm3BUKpNBB-xb_CJTcZ1UEC4NI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);